### ISSUE TITLE
Level 4 headers lack sufficient leading space

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#618] opened 2023-06-06 19:18 UTC
## Describe the bug

Level 4 headers lack leading space and therefore appears too close to the preceding content. The empty space that appears after the H4 should come before and the following content should be tighter to the H4.

![image](https://github.com/inclusive-design/idrc/assets/564762/74c864c4-be98-472a-b99e-530306f1fdf3)

![image](https://github.com/inclusive-design/idrc/assets/564762/a7ac9783-8c2e-4d8d-92da-6fe27019ec16)

**Comment by manzil-infinity180** [comment] 2023-08-21 17:30
assigned to me this issue , i want to work on it

**Comment by chosww** [comment] 2023-08-30 19:36
I can't reproduce this issue either, all h4 element seems to have margin-block-start set when I try it on local dev environment.

**Closed by chosww** 2023-08-30 19:36 UTC
Labels: bug, good first issue
